### ISSUE TITLE
Something Broke Today with Jupyter-DataProc

### ISSUE THREAD

**Issue by joshreuben456** [src-d/jgscm#4]
Was using jgscm on DataProc https://blog.sourced.tech/post/dataproc_jupyter/ for past week.
Sometime today , jupyter started prompting for authentication. same thing after redeploy. 
Also, logs are not appearing.

**Comment by vmarkovtsev** [comment]
Same problem on our side, I am figuring this out.

**Comment by vmarkovtsev** [comment]
A fast workaround is the explicit setting of the password in jupyter config.

**Comment by vmarkovtsev** [comment]
All right, say big thanks for breaking everything to https://github.com/jupyter/notebook/issues/1944

**Comment by vmarkovtsev** [comment]
Fixed in either gist or GCS. The solution was to add
```python
c.NotebookApp.token = ""
```
to the Jupyter config.
